language: dart

dart:
  - stable

os:
  - linux
  - osx
# TODO(sigurdm): our end2end test creates longer filenames than we can
# handle on windows. See https://github.com/dart-lang/sdk/issues/42416
#  - windows

dart_task:
  # Run the tests -- include the default-skipped presubmit tests
  # Run with concurrency = 1 â€“ the build-test command edits files, which might
  #   crash other tests run in parallel
  - test: --run-skipped -j 1
  - dartfmt
  - dartanalyzer: --fatal-infos .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
